#!/usr/bin/env bun
import { readFileSync, writeFileSync, statSync } from "node:fs";
import { extname } from "node:path";

const DRY = process.argv.includes("--dry");

interface Rule { pattern: RegExp; replacement: string; note: string }

const RULES: Rule[] = [
  // Crate identifiers (kebab-case) — Cargo.toml, README, docs
  { pattern: /\baion-agent\b/g,      replacement: "wcore-agent",      note: "crate aion-agent" },
  { pattern: /\baion-cli\b/g,        replacement: "wcore-cli",        note: "crate aion-cli" },
  { pattern: /\baion-compact\b/g,    replacement: "wcore-compact",    note: "crate aion-compact" },
  { pattern: /\baion-config\b/g,     replacement: "wcore-config",     note: "crate aion-config" },
  { pattern: /\baion-mcp\b/g,        replacement: "wcore-mcp",        note: "crate aion-mcp" },
  { pattern: /\baion-memory\b/g,     replacement: "wcore-memory",     note: "crate aion-memory" },
  { pattern: /\baion-protocol\b/g,   replacement: "wcore-protocol",   note: "crate aion-protocol" },
  { pattern: /\baion-providers\b/g,  replacement: "wcore-providers",  note: "crate aion-providers" },
  { pattern: /\baion-skills\b/g,     replacement: "wcore-skills",     note: "crate aion-skills" },
  { pattern: /\baion-tools\b/g,      replacement: "wcore-tools",      note: "crate aion-tools" },
  { pattern: /\baion-types\b/g,      replacement: "wcore-types",      note: "crate aion-types" },

  // Crate identifiers (snake_case) — Rust use statements / module refs
  { pattern: /\baion_agent\b/g,      replacement: "wcore_agent",      note: "snake aion_agent" },
  { pattern: /\baion_cli\b/g,        replacement: "wcore_cli",        note: "snake aion_cli" },
  { pattern: /\baion_compact\b/g,    replacement: "wcore_compact",    note: "snake aion_compact" },
  { pattern: /\baion_config\b/g,     replacement: "wcore_config",     note: "snake aion_config" },
  { pattern: /\baion_mcp\b/g,        replacement: "wcore_mcp",        note: "snake aion_mcp" },
  { pattern: /\baion_memory\b/g,     replacement: "wcore_memory",     note: "snake aion_memory" },
  { pattern: /\baion_protocol\b/g,   replacement: "wcore_protocol",   note: "snake aion_protocol" },
  { pattern: /\baion_providers\b/g,  replacement: "wcore_providers",  note: "snake aion_providers" },
  { pattern: /\baion_skills\b/g,     replacement: "wcore_skills",     note: "snake aion_skills" },
  { pattern: /\baion_tools\b/g,      replacement: "wcore_tools",      note: "snake aion_tools" },
  { pattern: /\baion_types\b/g,      replacement: "wcore_types",      note: "snake aion_types" },

  // Binary name + config paths
  { pattern: /\baionrs\b/g,          replacement: "genesis-core",     note: "binary name" },
  { pattern: /\.aionrs\.toml\b/g,    replacement: ".wcore.toml",      note: "config filename" },
  { pattern: /~\/\.aionrs\b/g,       replacement: "~/.wcore",         note: "user config dir" },

  // Product strings in non-license contexts (skip-line rule preserves copyright)
  { pattern: /\bAionRS\b/g,          replacement: "Genesis Core",     note: "product PascalCase" },
  { pattern: /\bAionrs\b/g,          replacement: "Genesis Core",     note: "product Mixed" },
];

const SKIP_LINE_REGEX = /Copyright|@license|Licensed under|All rights reserved/;

const SKIP_PATH_REGEXES: RegExp[] = [
  /^LICENSE$/, /^NOTICE/,
  /^\.git\//, /^target\//, /^dist\//,
  /^Cargo\.lock$/,  // regenerated by cargo
];

const BINARY_EXTS = new Set([".png",".jpg",".gif",".ico",".icns",".pdf",".node",".dylib",".so",".dll",".exe"]);

function shouldSkip(p: string): boolean {
  for (const re of SKIP_PATH_REGEXES) if (re.test(p)) return true;
  if (BINARY_EXTS.has(extname(p).toLowerCase())) return true;
  return false;
}

function processFile(path: string) {
  let content: string;
  try { content = readFileSync(path, "utf8"); } catch { return { changed: false, reps: new Map<string,number>() }; }
  const lines = content.split("\n");
  let dirty = false;
  const reps = new Map<string,number>();
  for (let i = 0; i < lines.length; i++) {
    if (SKIP_LINE_REGEX.test(lines[i])) continue;
    let next = lines[i];
    for (const r of RULES) {
      const before = next;
      next = next.replace(r.pattern, r.replacement);
      if (next !== before) {
        const m = before.match(r.pattern);
        if (m) reps.set(r.note, (reps.get(r.note) ?? 0) + m.length);
      }
    }
    if (next !== lines[i]) { lines[i] = next; dirty = true; }
  }
  if (dirty && !DRY) writeFileSync(path, lines.join("\n"));
  return { changed: dirty, reps };
}

function listFiles(): string[] {
  const proc = Bun.spawnSync(["git","ls-files"]);
  if (proc.exitCode !== 0) throw new Error("git ls-files failed");
  return new TextDecoder().decode(proc.stdout).split("\n").filter(p => p.length > 0);
}

const totals = new Map<string,number>(); let touched = 0, scanned = 0;
for (const p of listFiles()) {
  if (shouldSkip(p)) continue;
  try { if (!statSync(p).isFile()) continue; } catch { continue; }
  scanned++;
  const r = processFile(p);
  if (r.changed) {
    touched++;
    for (const [k,v] of r.reps) totals.set(k, (totals.get(k) ?? 0) + v);
  }
}
console.log(`scanned ${scanned}; ${DRY?"would touch":"touched"} ${touched}`);
for (const [k,v] of [...totals.entries()].sort((a,b)=>b[1]-a[1])) console.log(`  ${v.toString().padStart(5)}  ${k}`);
console.log(`total: ${[...totals.values()].reduce((a,b)=>a+b,0)}`);
